services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./BaseContagemKafka.sql:/tmp/BaseContagemKafka.sql
      - ./init-sqlserver.sh:/tmp/init-sqlserver.sh
    command: /bin/bash ./tmp/init-sqlserver.sh
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  contagemredis:
    image: renatogroffe/apicontagem-dotnet7-opentelemetry-jaeger-redis:1
    depends_on:
      - redis
      - jaeger
    environment:
      ConnectionStrings__Redis: redis
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
    ports:
      - "6100:80"
  workerkafka:
    image: renatogroffe/workercontagem-dotnet7-opentelemetry-jaeger-kafka:3
    depends_on:
      - zookeeper
      - kafka
      - jaeger
    environment:
      ApacheKafka__Topic: topic-contagem
      ApacheKafka__Host: kafka:29092
      ApacheKafka__GroupId: workercontagem
      ApacheKafka__WaitingTimeInitialization: 11000
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
      ConnectionStrings__BaseContagem: Server=sqlserver;Database=BaseContagemKafka;User Id=sa;Password=SqlServer2019!;TrustServerCertificate=True;
  contagemkafka:
    image: renatogroffe/apicontagem-dotnet7-opentelemetry-jaeger-kafka:5
    depends_on:
      - zookeeper
      - kafka
      - jaeger
      - workerkafka
    environment:
      ApacheKafka__Topic: topic-contagem
      ApacheKafka__Host: kafka:29092
      ApacheKafka__WaitingTimeInitialization: 14000
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
    ports:
      - "6150:80"
  orquestracaohttp:
    image: renatogroffe/apicontagem-dotnet7-opentelemetry-jaeger-httpinstrumentation:1
    depends_on:
      - jaeger
      - contagemredis
      - contagemkafka
      - workerkafka
    environment:
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
      ApiContagemRedis: http://contagemredis/contador
      ApiContagemKafka: http://contagemkafka/contador
    ports:
      - "6050:80"